### ISSUE TITLE
Lights only come on and never go off?

### ISSUE THREAD

**Issue by redpola** [bjoluc/cubase-mcu-midiremote#14]
I'm new to this so apologies if this is naivety on my part.

I've set up the script as documented and my x-touch is working... in a fashion. It seems that every button I press that illuminates an LED results in the correct operation but that LED never goes out.

As an illustrative example if I load a project, hit "play" and then select each of the current 8 tracks, I am left with all 8 track select LEDs on. This makes my x-touch pretty unusable since after a small amount of work so many lights are lit I have no idea what I'm doing. As another example if I  tap the "cycle" key, cycling is correctly turned on or off but the lights remains on.

Is this a configuration option I've got wrong? A bug in the script? My x-touch is on the latest firmware and is set to MCU mode.

**Comment by redpola** [comment]
I think this may be a Cubase problem. Please keep this open until I comment more.

**Comment by bjoluc** [comment]
Thanks for opening this @redpola! Any chance it's fixed by c7d5597 (compiled scripts [here](https://github.com/bjoluc/cubase-mcu-midiremote/suites/15408212030/artifacts/879857976))?

> Is this a configuration option I've got wrong? A bug in the script? My x-touch is on the latest firmware and is set to MCU mode.

Unless you enabled Christmas tree mode, you did everything right :upside_down_face:

**Comment by redpola** [comment]
I'll take a look asap. Note that this sudden change in behaviour has been raised with Steinberg.

**Comment by redpola** [comment]
I just checked your change notes and it aligns with what I've read elsewhere. Sending 0xff is wrong. :) Will test and report back.

**Comment by redpola** [comment]
This is a duplicate of #15
