### ISSUE TITLE
Script is sending the wrong Velocity Value (which is being covered by C12, but may not be by future versions).

### ISSUE THREAD

**Issue by djaychela** [bjoluc/cubase-mcu-midiremote#15]
I don't want to break an NDA, but let's just say I know that this will not work in a future version of Cubase (I think that C12 is masking this error, and a later version will not).

I understand Python well, but don't have any typescript skills, so couldn't do a PR, however, I think in this file:

`src/midi/PortPair.ts`

There is an issue which is a simple fix:

`output.sendMidi(context, [0x90, pitch, +Boolean(velocity) * 0xff]);`

Should read

`output.sendMidi(context, [0x90, pitch, +Boolean(velocity) * 0x7f]);`

So that the script tries to send 127 as the maximum value, not 255.  Then it will work.

**Comment by djaychela** [comment]
I've made a manual change to the compiled JS file (line 4146 for me) and it works fine, BTW.

**Comment by bjoluc** [comment]
A message from the future, exciting! Thanks for the heads-up @djaychela, and what a silly mistake :facepalm: Fixed by c7d5597 which will be included in 1.7.0 soon. By the way, any words on the 2024 US election yet?
