### ISSUE TITLE
déplacement de pistes cubase 12.0.70

### ISSUE THREAD

**Issue by danimusicos** [bjoluc/cubase-mcu-midiremote#16]
Bonjour, J'ai remarqué un bug qui fige cubase dès qu'on veut déplacer une piste.

**Comment by bjoluc** [comment]
Hi @danimusicos, that's odd. Are you using the latest script version (1.6.0 at the moment)?

**Comment by danimusicos** [comment]
Oui 1,60

**Comment by bjoluc** [comment]
May I ask for some precise repro steps then? It is not really clear to me from your initial description how I can reproduce the crash. Also, it'd make my life a bit easier if you could translate your messages to English (for instance using https://www.deepl.com/translator) before posting them here, so I don't have to do that (sorry, I don't speak French) :slightly_smiling_face:

**Comment by danimusicos** [comment]
Hello, in fact this is a random malfunction, as soon as I move a track for example to put it lower or higher, it happens that cubase freezes forcing me to close it abruptly and restart it. I don't know why it does it on some projects and not others. For example, yesterday I opened various projects and it didn't do it. In addition, functions such as save and advance are often no longer functional. I have to deactivate and reactivate, but I often have to restart cubase. I'll have to think about making a video recording for you to see, but that's also random. Thanks for your time. I hope the translation works for you. Best regards.

Bonjour, en fait il s'agit d'un dysfonctionnement aléatoire, dès que je déplace une piste par exemple pour la mettre plus bas ou plus haut, il arrive que cubase se fige m'obligeant à le fermer brutalement et à le redémarrer. Je ne sais pas pourquoi cela se produit sur certains projets et pas sur d'autres. Par exemple, hier j'ai ouvert plusieurs projets et cela ne s'est pas produit. En outre, les fonctions telles que sauvegarder et avancer ne fonctionnent souvent plus. Je dois désactiver et réactiver, mais je dois souvent redémarrer cubase. Il faudra que je pense à faire un enregistrement vidéo pour que vous puissiez voir, mais c'est aussi aléatoire. Merci de m'avoir accordé un peu de votre temps. J'espère que la traduction fonctionnera pour vous. Je vous prie d'agréer, Madame, Monsieur, l'expression de mes salutations distinguées.

**Comment by danimusicos** [comment]
Good evening, I've noticed a curious problem: the motor button on the control surface doesn't work, since when it's deactivated the cursors on the controller slices continue to move. Best regards.

Bonsoir, j'ai remarqué un curieux problème : le bouton moteur de la surface de contrôle ne fonctionne pas, puisque lorsqu'il est désactivé, les curseurs sur les tranches du contrôleur continuent à se déplacer.

**Comment by danimusicos** [comment]
> Good evening, I've noticed a curious problem: the motor button on the control surface doesn't work, since when it's deactivated the cursors on the controller slices continue to move. Best regards.
> 
> Bonsoir, j'ai remarqué un curieux problème : le bouton moteur de la surface de contrôle ne fonctionne pas, puisque lorsqu'il est désactivé, les curseurs sur les tranches du contrôleur continuent à se déplacer.

çà pourrait une anomalie consécutive à une ancienne version du fichiers qui comporte des automation de volume.

This could be an anomaly resulting from an old version of the file which includes volume automation.

**Comment by danimusicos** [comment]
hello on 1.7.0: Like 1.6 the change on the smpte button modifies on cubase but not on the xtouch.

bonjour sur la 1.7.0 : Comme la 1.6 le changement sur le bouton smpte modifie sur cubase mais pas sur la xtouch.

**Comment by bjoluc** [comment]
That's great news at least – I double-checked the motor button works in all recent versions.

> I'll have to think about making a video recording for you to see, but that's also random.

That would be very helpful indeed – I never heard or experienced what you describe :confused:

> I hope the translation works for you.

Perfectly fine, thanks!

> the change on the smpte button modifies on cubase but not on the xtouch.

Interesting, couldn't reproduce so far but will take a look when I get to it.

**Comment by danimusicos** [comment]
Hello, in fact if I stop Cubase and click on the smpt button, then I have the time of the song, however as soon as Cubase is running it no longer works.
