### ISSUE TITLE
Feature Suggestion: Invert EQ Gain Action

### ISSUE THREAD

**Issue by mbfranck** [bjoluc/cubase-mcu-midiremote#17]
The CC121 has a handy feature, quote from documentation:

"EQ gain inverse: You can invert the gain curve(s) of individual or entire EQ band(s) on Cubase by using the [ON] button."

Maybe you could add this to one of the encoder press actions (pressing the "gain" encoder might be a logical choice).

**Comment by mbfranck** [comment]
After using the EQ pages for some hours and incorporating the above idea, I imagined an "all-in-one" EQ page 3:

Each EQ band is represented by two encoders and two faders (so with eight strips, we may cover 4 bands).

Example suggestions for low EQ:

- Encoder 1 Push: Band on / off
- Encoder 2 Push: Gain Invert
- Encoder 1 Rotation: EQ Type
- Encoder 2 Rotation: Q
- Fader 1: Frequency
- Fader 2: Gain

Strips 3 & 4 / 5 & 6 / 7 & 8 are assigned accordingly for the other EQ bands. I feel like it would be great to have the complete EQ parameter set covered on a single page this way.

I unfortunately cannot tell whether this is possible via the API, but I wanted to share the thought. Looking forward to hearing your opinion on this!

**Comment by bjoluc** [comment]
Hi @mbfranck,

thanks for opening this! I agree a way to invert an EQ band's gain would be awesome and I also think pressing the gain encoders should be it. I checked there are no builtin commands that we could bind to for this, but we might succeed setting the encoder value programmatically :sunglasses:

Re your second suggestion: While certainly useful for some, an EQ page involving faders would violate the fundamental Mackie Control concept that faders always control track volumes unless FLIP mode is active, so I'm a bit hesitant to consider it. But you can always craft your own mapping page with the Mapping Assistant :slightly_smiling_face:

**Comment by mbfranck** [comment]
Hi @bjoluc, many thanks for your comments. Happy to see you like the idea of gain invert. Maybe you'll find a way or any future API will provide this possibility. 

Regarding another EQ page: I can completely understand your hesitation regarding the faders and UX consistency. Will try mapping it by myself, thanks for that hint :)
