### ISSUE TITLE
choisir temps écoulé version 1.70 et 1.80

### ISSUE THREAD

**Issue by danimusicos** [bjoluc/cubase-mcu-midiremote#18]
Bonjour, quand j'appuis sur la xtouch pour avoir la durée du morceau, on voit l'information dans cubase 12.0.70, mais pas sur la xtouch, çà n'inscrit pas la même chose que cubase.
cdt

Hello, when I press the xtouch to get the duration of the song, we see the information in cubase 12.0.70, but not on the xtouch, it does not register the same thing as cubase.
cdt

**Comment by bjoluc** [comment]
Hi @danimusicos,
once again, I'm afraid I can't reproduce what you describe – no matter what I try, the time display keeps working like it should. Do you have any precise steps or video how to reproduce?

**Comment by danimusicos** [comment]
Bonjour,

bizarre, le bouton commandant le choix ne fonctionne plus !!!
j'ai essayé sur d'autres projets

Hello

Strange, the button commanding the choice no longer works!!
I've tried it on other projects

cordialement
________________________________
De : bjoluc ***@***.***>
Envoyé : lundi 27 novembre 2023 15:55
À : bjoluc/cubase-mcu-midiremote ***@***.***>
Cc : danimusicos ***@***.***>; Mention ***@***.***>
Objet : Re: [bjoluc/cubase-mcu-midiremote] choisir temps écoulé version 1.70 et 1.80 (Issue #18)


Hi @danimusicos<https://github.com/danimusicos>,
once again, I'm afraid I can't reproduce what you describe – no matter what I try, the time display keeps working like it should. Do you have any precise steps or video how to reproduce?

**Comment by bjoluc** [comment]
The SMPTE/Beats button is mapped to toggle between primary and secondary time format – maybe your project's secondary time format does not differ from the primary format?

**Comment by bjoluc** [comment]
Did you try [resetting the script's user mappings](https://forums.steinberg.net/t/x-touch-extender-midi-remote-script-mcu-mode/831493/88) in case anything is messed up with them?

**Comment by danimusicos** [comment]
no, i'm looking
________________________________
De : bjoluc ***@***.***>
Envoyé : mardi 28 novembre 2023 18:27
À : bjoluc/cubase-mcu-midiremote ***@***.***>
Cc : danimusicos ***@***.***>; Mention ***@***.***>
Objet : Re: [bjoluc/cubase-mcu-midiremote] choisir temps écoulé version 1.70 et 1.80 (Issue #18)


Did you try resetting the script's user mappings<https://forums.steinberg.net/t/x-touch-extender-midi-remote-script-mcu-mode/831493/88> in case anything is messed up with them?

**Comment by danimusicos** [comment]
I've tried to reassign the function, but nothing changes. On the other hand, as on the 1.70 and the previous versions, I had integrated other functions, I did the same with the 1.80.
________________________________
De : bjoluc ***@***.***>
Envoyé : mardi 28 novembre 2023 18:27
À : bjoluc/cubase-mcu-midiremote ***@***.***>
Cc : danimusicos ***@***.***>; Mention ***@***.***>
Objet : Re: [bjoluc/cubase-mcu-midiremote] choisir temps écoulé version 1.70 et 1.80 (Issue #18)


Did you try resetting the script's user mappings<https://forums.steinberg.net/t/x-touch-extender-midi-remote-script-mcu-mode/831493/88> in case anything is messed up with them?

**Comment by danimusicos** [comment]
yes
________________________________
De : bjoluc ***@***.***>
Envoyé : mardi 28 novembre 2023 18:43
À : bjoluc/cubase-mcu-midiremote ***@***.***>
Cc : danimusicos ***@***.***>; Mention ***@***.***>
Objet : Re: [bjoluc/cubase-mcu-midiremote] choisir temps écoulé version 1.70 et 1.80 (Issue #18)


Strange; now, if you press the . key in Cubase, does it switch time formats?

**Comment by bjoluc** [comment]
And the X-Touch timecode display still does not follow along?

**Comment by danimusicos** [comment]
I closed Cubase, turned off the 2 Xtouch, restarted, but it's the same. Can I send you the script I have?
________________________________
De : bjoluc ***@***.***>
Envoyé : mardi 28 novembre 2023 18:43
À : bjoluc/cubase-mcu-midiremote ***@***.***>
Cc : danimusicos ***@***.***>; Mention ***@***.***>
Objet : Re: [bjoluc/cubase-mcu-midiremote] choisir temps écoulé version 1.70 et 1.80 (Issue #18)


Strange; now, if you press the . key in Cubase, does it switch time formats?

**Comment by bjoluc** [comment]
Are you up for a quick Teamviewer session? :smile:

**Comment by bjoluc** [comment]
Oh, sorry, how stupid of me :see_no_evil:

**Comment by danimusicos** [comment]
yes
________________________________
De : bjoluc ***@***.***>
Envoyé : mardi 28 novembre 2023 18:52
À : bjoluc/cubase-mcu-midiremote ***@***.***>
Cc : danimusicos ***@***.***>; Mention ***@***.***>
Objet : Re: [bjoluc/cubase-mcu-midiremote] choisir temps écoulé version 1.70 et 1.80 (Issue #18)


Are you up for a quick Teamviewer session? 😄

**Comment by bjoluc** [comment]
I might as well misunderstand your issue – maybe @limageurpublic can chime in here (no probs if not and sorry for the direct mention)? In case this is a Cubase-localization-related problem, maybe you are facing it too @limageurpublic?

**Comment by danimusicos** [comment]
Maybe the public imager could. Right now I'm trying various things but it doesn't seem to do anything more. On Cuba, the select binary time format function controls the xtouch well, not the other way around


________________________________
De : bjoluc ***@***.***>
Envoyé : mardi 28 novembre 2023 19:04
À : bjoluc/cubase-mcu-midiremote ***@***.***>
Cc : danimusicos ***@***.***>; Mention ***@***.***>
Objet : Re: [bjoluc/cubase-mcu-midiremote] choisir temps écoulé version 1.70 et 1.80 (Issue #18)


I might as well misunderstand your issue – maybe @limageurpublic<https://github.com/limageurpublic> can chime in here (no probs if not and sorry for the direct mention)? In case this is a Cubase-localization-related problem, maybe you are facing it too @limageurpublic<https://github.com/limageurpublic>?

**Comment by limageurpublic** [comment]
Hi,
Je peux aider ?
Can I help anybody ?
à suivre...
Kind regards

**Comment by danimusicos** [comment]
Bonsoir,

Peut-être. J'ai donc un souci avec l'utilisation de cubase 12.0.70. windows 10.

Quand j'appuie sur le bouton de la xtouch pendant le démarrage de mon projet qui permet de voir différentes configurations de durée : secondes, smpt, etc, celle-ci devrait s'afficher normalement. Or, çà le fait bien en appuyant sur le bouton xtouch et active bien sur cubase pas sur la xtouch. Par contre si j'arrête çà fonctionne en appuyant sur xtouch.
L'inverse est identique si je sélectionne à partir de cubase, la xtouch ne comprend pas la commande.
C'est un peu complexe.
Cordialement
Daniel
________________________________
De : limageurpublic ***@***.***>
Envoyé : mercredi 29 novembre 2023 21:00
À : bjoluc/cubase-mcu-midiremote ***@***.***>
Cc : danimusicos ***@***.***>; Mention ***@***.***>
Objet : Re: [bjoluc/cubase-mcu-midiremote] choisir temps écoulé version 1.70 et 1.80 (Issue #18)


Hi,
Je peux aider ?
Can I help anybody ?
à suivre...
Kind regards

**Comment by limageurpublic** [comment]
Hello,
Désolé, je ne comprends pas ta manip, je n'utilise pas ces fonctionnalités
sur xtouch...ou alors je n'ai pas bien compris ton problème.
À suivre...
Musicalement.

Le mer. 29 nov. 2023, 21:22, danimusicos ***@***.***> a
écrit :

**Comment by limageurpublic** [comment]
Hope everything is ok for you Bjorn, please give some news from you. Kind regards

**Comment by bjoluc** [comment]
By the way, I've added a "Troubleshooting" section in the Readme. Don't know if that's of any help to you, but thought I'd share it here: https://github.com/bjoluc/cubase-mcu-midiremote#troubleshooting

**Comment by danimusicos** [comment]
merci !!!!!!
________________________________
De : bjoluc ***@***.***>
Envoyé : vendredi 12 janvier 2024 17:06
À : bjoluc/cubase-mcu-midiremote ***@***.***>
Cc : danimusicos ***@***.***>; Mention ***@***.***>
Objet : Re: [bjoluc/cubase-mcu-midiremote] choisir temps écoulé version 1.70 et 1.80 (Issue #18)


By the way, I've added a "Troubleshooting" section in the Readme. Don't know if that's of any help to you, but thought I'd share it here: https://github.com/bjoluc/cubase-mcu-midiremote#troubleshooting

**Comment by danimusicos** [comment]
super !!!! merci
________________________________
De : bjoluc ***@***.***>
Envoyé : vendredi 12 janvier 2024 17:06
À : bjoluc/cubase-mcu-midiremote ***@***.***>
Cc : danimusicos ***@***.***>; Mention ***@***.***>
Objet : Re: [bjoluc/cubase-mcu-midiremote] choisir temps écoulé version 1.70 et 1.80 (Issue #18)


By the way, I've added a "Troubleshooting" section in the Readme. Don't know if that's of any help to you, but thought I'd share it here: https://github.com/bjoluc/cubase-mcu-midiremote#troubleshooting
