### ISSUE TITLE
cubase 13

### ISSUE THREAD

**Issue by danimusicos** [bjoluc/cubase-mcu-midiremote#21]
Hello, my first feedback:

No more colors on the control panel, forward, backward, play, record, stop. finally everywhere.

Changed the way to configure the f1 to F8 and master keys. Before you could do it easily by choosing the desired key on the xtouch and then the corresponding function in Cubase and applying it. Now everything can be done via the xtouch with the mouse on the Cubase xtouch. as I have a control pedal that I plug into the xtouch I can no longer affect it

Bonjour, mes premiers retours : 

Les couleurs sur panneau de contrôle vont et viennent : avance, retour, jouer, enregistrement, stop. enfin partout .

Modification de la façon de paramétrer les touches f1 à F8 et master. Avant on pouvait le faire facilement en choisissant sur la xtouch la touche voulue et ensuite la fonction correspondante dans Cubase et en appliquant. Maintenant tout de se faire via la xtouch avec la souris sur la xtouch de Cubase. comme j'ai une pédale de contrôle que je branche sur la xtouch je ne peux plus l'affecter.

Daniel

**Comment by bjoluc** [comment]
Hey @danimusicos,
> Changed the way to configure the f1 to F8 and master keys. Before you could do it easily by choosing the desired key on the xtouch and then the corresponding function in Cubase and applying it. Now everything can be done via the xtouch with the mouse on the Cubase xtouch.

I just tried this with Cubase 13.0.20 and I can replicate what you describe: Pressing the function keys opens the mapping assistant, but it doesn't select the corresponding function button in the editor anymore. I guess it's up to Cubase to fix this. I'll post on their forums about it.

> as I have a control pedal that I plug into the xtouch I can no longer affect it

The pedals are also available visually in Cubase (in the same order as the hardware connectors), so mapping them should still work:
![pedal-surface-elements](https://github.com/bjoluc/cubase-mcu-midiremote/assets/25661029/19b21f7a-c84b-4b20-a9b2-a396d37b60cf)

Cheers!
