### ISSUE TITLE
Output Fader only updates in one direction? 

### ISSUE THREAD

**Issue by kocomputer** [bjoluc/cubase-mcu-midiremote#26]
Hey. Firstly THANK YOU!!!! You are an absolute superstar for doing this, and making a lot of people very happy to get channel colours working on the X-Touch (& others) with Cubase - something we've wanted for years, and Behringer/Steinberg should have done long before now!

I may have gotten something wrong in my configuration (or accidently edited something somehow) / maybe it's intentional / or  maybe I have found a minor bug.
So thought I'd flag it - so you can correct (if possible/desired), or if it's actually intended behaviour maybe you could add a comment in the release notes to guide others.

cubase-mcu-midiremote: V1.9.0
Cubase Pro: V12.0.70.
X-Touch - Standard (No Extenders).

I switched the "mapMainFaderToControlRoom" flag to **false** in the .js file as directed in the release notes - I generally use the 'master' output rather than ControlRoom (which I really must learn to use!).

I noticed that all my channel faders behaved as expected, but my Master Output Fader (Fader-9 = "Main" on the X-Touch) DOES correctly control the mixer master channel. BUT, if I update the master channel volume using the mouse inside Cubase, the fader on the X-Touch does not move to reflect the change.

A bit of investigating, in the Remote Mapping Assistant, and I spotted the Output Fader is configured differently to the other faders - it is marked as **Project** instead of **Global** - and **Value Mod** also set to "Scaled" rather than "Jump."

Updated and saved these values and bingo, everything working perfectly - two-way-mirroring restored :o)

Cheers, Keep up the amazing work!!
Keith

**Comment by bjoluc** [comment]
Hi @kocomputer,

thanks so much for the kind words and for taking the time to report this! I just double-checked that the main fader is properly set up, so

> accidently edited something somehow

might be the reason for this in your case.

Thanks again!
