### ISSUE TITLE
MIDI communication issues with rtpMIDI

### ISSUE THREAD

**Issue by Pendejo10** [bjoluc/cubase-mcu-midiremote#27]
Configuration:

Cubase 13.020
Main Device with two extenders connected via ethernet using rtpMIDI
Device: {"extender", "extender", "main"}

Everything seems to be connected very well, parameter are set correctly on all controllers (rarely a fader is wrong) but one of the three controllers cannot send any parameter to the DAW (no Fader, buttons nor pan)

In most of the cases it is the first extender, which cannot send parameter but it is always reflecting the correct status, e.g. if I click "Solo" on another controller the mute state appears on all controllers correctly.

The reload of the script in the MIDI Remote Manager doesn't help.

**Comment by Pendejo10** [comment]
I have resolved the problem and it is **not** related to the script itself.

Obviously, the script does a much quicker communication than the Mackie controller, which I have used before in Cubase. Therefore the response did not came in the right timing (I guess). I have finally change the communication speed of rtpMIDI. This fixed all issues, like wrong fader position and not responding controllers. Maybe this is an helpful information for other users, who are using the X-Touch via ethernet.

So I apologize for any confusion.

**Comment by bjoluc** [comment]
This is awesome news @Pendejo10 – thanks so much for sharing it! I've heard of similar issues from other rtpMIDI users, so your finding might also help them (@JDubs73?) :tada:
If I were to add a troubleshooting entry for this, are there any specific instructions I should provide for changing the speed?

**Comment by Pendejo10** [comment]
I set the "Standard-Bitrate" to 250000. Important to know is, that there is a bug in the UI of rtpMIDI. The bitrate is not reflected in the UI properly, although the value is set to maximum it always shows the lowest value. But if it has been set once, the value is stored correctly.
BTW, the parameters are stored in the registry (Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Tobias Erichsen\rtpMIDI).

**Comment by JDubs73** [comment]
I appreciate the tips, thanks! Sent from my iPhoneOn Feb 6, 2024, at 2:35 PM, Pendejo10 ***@***.***> wrote:﻿
I set the "Standard-Bitrate" to 250000. Important to know is, that there is a bug in the UI of rtpMIDI. The bitrate is not reflected in the UI properly, although the value is set to maximum it always shows the lowest value. But if it has been set once, the value is stored correctly.
BTW, the parameters are stored in the registry (Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Tobias Erichsen\rtpMIDI).
