### ISSUE TITLE
Push Encoders not working for buttons in plugins/inserts

### ISSUE THREAD

**Issue by TheImproof** [bjoluc/cubase-mcu-midiremote#32]
I'm working with Cubase 13.0.21 and the icon qcon pro g2, firmware is 1.15

In some plugins are toggleable parameters like "Auto Release" in the compressor. I can't modify the state with the encoders of my controller, regardless if I turn or push them. Is this a limitation or am I doing something wrong?

**Comment by bjoluc** [comment]
Thanks @TheImproof! You're doing everything right. This is a known issue introduced in Cubase 13 (Cubase 12 works fine). I hope it will be fixed soon as it is quite annoying...
