### ISSUE TITLE
X-touch stops sending.

### ISSUE THREAD

**Issue by MrKeyes1979** [bjoluc/cubase-mcu-midiremote#34]
I've noticed periodically that the x-touch stops sending to Cubase. It still receives commands (faders move, transport lights, etc) but fader movements and other commands stops sending. I'm not sure if it's a hardware issue, script issue, or cubase issue.

Windows 10 Pro 22H2
X-Touch Universal firmware 1.22
Cubase Pro 13.0.30
I downloaded and installed newest script 1-24-24

**Comment by bjoluc** [comment]
Thanks for reporting @MrKeyes1979! I've experienced this myself a few times in the past – in my case it was related to the issues described at https://forums.steinberg.net/t/midi-remote-control-stops-working-when-i-plug-in-another-midi-device/873065. Seems to be a Cubase issue though, hence closing the issue.
