### ISSUE TITLE
Encoder button issues

### ISSUE THREAD

**Issue by fischnek** [bjoluc/cubase-mcu-midiremote#36]
Hi,
I noticed that the encoder assign buttons (pan, EQ, send etc.) only work when i press them together with SHIFT. Also, the assignment display doesn’t shows the sub page the numbering.
I experimented and found the following about the “encoder buttons” problem:
1.	Basically the problem is **project dependent**. The encoder buttons work fine when opening a new project or an existing project.
2.	However, when opening certain projects, the operation stops. And when this happens, projects that were already working don’t work anymore.
3.	If I restart Cubase (the controller doesn’t need to be restarted), operation is restored as long as I don’t open any project that breaks operation.
4.	I have tested the project causing the error. I deleted all the tracks in sequence, first the instrument, then midi, audio, etc. In the end the project was completely empty, I even deleted the pool: but the error persists for that project.
5.	I noticed: for OK projects, when I press the encoder buttons, the “last touhed control” parameter (shown on the midi remote page) shows at the moment of pressing what action is being done (for example: Activate Subpage “EQ 1”, but when the button is released, it automatically and immediately returns to “Record (Transport)”. For those projects where there is a problem, when the EQ is pressed, the button lights up but no change is made, and for “Last touched control” the value "Activate Subpage “EQ 1” remains, it does not automatically return to “Record (Transport)”. If I press the record button, the recording starts AND switches to EQ mode. After pressing any encoder, if I press the record button, it will switch to the desired mode.
That’s it so far. It would be nice if this would help solve it.

**Comment by fischnek** [comment]
[empty_with_issue.zip](https://github.com/bjoluc/cubase-mcu-midiremote/files/15210913/empty_with_issue.zip)
Hi Bjoluc,

please find attached. Beside the above mentioned issues, the zoom buttons have also malfunction.
Please let me know how can I support you to find the prolem. Otherwise, it would be nice know once you have the solution.

thank you

fischnek

**Comment by bjoluc** [comment]
Thanks @fischnek! With your help, I was able to reproduce the issue and find a workaround: Disabling and re-enabling the script helps! :tada:

![disable-enable-controller-script](https://github.com/bjoluc/cubase-mcu-midiremote/assets/25661029/1431b250-a578-4f2b-ac65-d34a4b668b29)

I'm adding this to the troubleshooting section, including the GIF.

When you save an issue project after doing this, opening the project again later doesn't cause the issue again. Hurray!

**Comment by fischnek** [comment]
Hi Bjoluc,

confirmed! The solution works. For me, not even a restart or re-open is
needed: it works instantly.
It is a pity that I was not able to find this solution by myself.
Thank you very much

cheers

fis


bjoluc ***@***.***> ezt írta (időpont: 2024. máj. 25., Szo,
12:10):
