### ISSUE TITLE
Cubase 13 Pro anomalies still present with latest script

### ISSUE THREAD

**Issue by danimusicos** [bjoluc/cubase-mcu-midiremote#41]
Bonjour, le dernier script n'a pas réglé les problèmes d'appui des boutons qui ne s'allument pas dans cubase 13.
Cycle, scrub, la touche pour monter descendre aller de gauche ou droite et réduire les pistes. Le voyant de sélection des pistes est très perturbé il s'allume quand il veut.  merci

**Comment by bjoluc** [comment]
Hi @danimusicos,
could you try [disabling and re-enabling](https://github.com/bjoluc/cubase-mcu-midiremote?tab=readme-ov-file#how-to-disable-and-re-enable-a-controller-script) the script? I have never experienced what you describe nor has anyone else reported it, so my only idea about this is [this section](https://github.com/bjoluc/cubase-mcu-midiremote?tab=readme-ov-file#some-buttons-do-not-work-as-expected) from the FAQ – sorry!

**Comment by bjoluc** [comment]
> Le voyant de sélection des pistes est très perturbé il s'allume quand il veut.

Hm, maybe also an instance of [an Cubase MCU device set up with the same ports](https://github.com/bjoluc/cubase-mcu-midiremote?tab=readme-ov-file#some-displays-are-lagging-or-faders-are-stuttering-heavily-when-reading-automation)?

**Comment by danimusicos** [comment]
Bonjoujr, quand çà fonctionne mal, de désactive et réactive. Par contre avec cubase 12, c'espt parfait. Seul cubase 13 me pose problème.

**Comment by bjoluc** [comment]
Thanks for the update. I hope Steinberg will fix the occasional Cubase 13 issues – I've also seen reports about them with other user scripts. Glad you've found a workaround at least. Cheers!

**Comment by danimusicos** [comment]
Bjr, c'est grâce à vous !
