### ISSUE TITLE
cubase 13.0.50et cubase  14  xtouch ne se lance plus automatiquement

### ISSUE THREAD

**Issue by danimusicos** [bjoluc/cubase-mcu-midiremote#51]
bjr, la mise à jour de cubase 13 empêche le lancement de xtouch, obligé de refaire manuellement à chaque fois.

**Comment by danimusicos** [comment]
> bjr, la mise à jour de cubase 13 et la nouvelle mise à jour cubase 14 ne permettent plus le lancement automatique de xtouch, à l'ouverture d'un projet. Obligé de refaire manuellement à chaque fois. Sur cubase 12 çà fonctionne au poil.

**Comment by danimusicos** [comment]
> bjr, la mise à jour de cubase 13 et la nouvelle mise à jour cubase 14 ne permettent plus le lancement automatique de xtouch, à l'ouverture d'un projet. Obligé de refaire manuellement à chaque fois. Sur cubase 12 çà fonctionne au poil.

**Comment by Pendejo10** [comment]
I can confirm this issue. I have it on both of my Systems, one on MAC the other on Windows. Other MIDI controllers are not behaving like this.

**Comment by danimusicos** [comment]
La cubase 14.010 Après de nombreuses manipulations a permis le lancement dès l'ouverture d'un projet. Je suis incapable de savoir comment j'ai réussi à refaire fonctionner. Quant à cubase 13.0.51 la mise à jour échoue erreur 1638. A suivre...

**Comment by danimusicos** [comment]
La cubase 14.010 Après de nombreuses manipulations a permis le lancement dès l'ouverture d'un projet. Je suis incapable de savoir comment j'ai réussi à refaire fonctionner. Quant à cubase 13.0.51
