### ISSUE TITLE
Support adaptive jogwheel speed

### ISSUE THREAD

**Issue by bjoluc** [bjoluc/cubase-mcu-midiremote#8]
I'm a Qcon Pro G2 user, and surprisingly the Behringer Xtouch script works like a charm on my surface. The only thing I miss compared to the Mackiecontrol is the adaptive jogwhell speed. When you scroll fast, it scrolls fast, when you scroll slowly it is more precise. In your script the jog is locked at the grid settings. Is there on option that could change that behaviour ? (sorry if I am on the wrong place to ask this)

_Originally posted by @toto-polo in https://github.com/bjoluc/cubase-xtouch-midiremote/issues/7#issuecomment-1584122032_

**Comment by bjoluc** [comment]
Hey @toto-polo,
I'm glad to hear there are more Qcon Pro G2 users out there – feel free to download the [latest draft from #7](https://github.com/bjoluc/cubase-xtouch-midiremote/suites/13435474675/artifacts/736528193) and give it a try :slightly_smiling_face:

Since the MIDI Remote API has no builtin jogwheel implementation, I had to build a substitution: When you turn the jog wheel left/right, the `"Transport" > "Nudge Cursor Left/Right"` key command is triggered (unless you have jog mode enabled, then it's `"Transport" > "Jog Left/Right"`). In the script, I am able to differentiate between slow and fast jogging, but I didn't find a way to translate that into key commands. Sadly, triggering the key command twice on fast movements didn't nudge/jog stably.

I don't think there are more advanced key commands for our use case (unless you know some maybe?). Let's leave this issue open for reference, although it might not be fixable with the current MR API :confused:

**Comment by toto-polo** [comment]
Thanks for this answer and reflexions about it ! If there is the possibility of 2 differents speeds maybe the slow one could be set to "Transport" > "Nudge Cursor Left/Right" like you did, and the fast one to rewind / fastforward. 

Like on keybaord + / - buttons for fast forward and cmd + /- for precise mouvements. 

Is it possible to do that ?

**Comment by bjoluc** [comment]
Closing this as not planned/stale. While doable in general, there seems to be no way to make this work relative to the beat grid ("Nudge Cursor ±5/10/20 Seconds" doesn't cut it).
