### ISSUE TITLE
problems with Skrip 1.5 in Cubase 12.0.60 Pro

### ISSUE THREAD

**Issue by LB336** [bjoluc/cubase-mcu-midiremote#9]
Hello,
I have 2 problems with Skrip 1.5. 
1. under the encoder assign "Dyn/Fx/Aux or Inst I can not edit the "VST Quick Controls". It only shows the track names and that there are 6 subpages. 
I have then installed the version 1.42 again, there it works.
I then installed the version 1.5 again and wanted to take over the setting of 1.42. This did not work at all. 

Now we come to the 2. problem. 
I wanted to reset everything again, which did not work at first. No matter what I did, whether deleting the script and copying it back in, disconnecting the x-Touch from the USB, deleting the script in Midi-Remote. Nothing deletes the wrong script. When I restarted, the old script that I had edited was always displayed. 
Only when I completely uninstalled Cubase and reinstalled also worked that the 1.5 script, as it should be. 
I think that this is not useful and wanted.

I work with 
Win 11 Pro version 22H2 operating system build 22621.1848
Cubase Pro 12.0.60    

Many greetings 
Lothar Berg

**Comment by bjoluc** [comment]
Hi @LB336,

thanks for reporting. I think [this post](https://forums.steinberg.net/t/831493/88) on the Steinberg forum might help you with problem 2 if I understand your description correctly. Unfortunately, I cannot replicate problem 1 on Cubase Pro 12.0.6. My testbed VM runs Windows 10, but I'd be surprised if that made any difference. Maybe the malfunction is connected to some persistent user mappings? Can you try deleting the script's MIDI Remote user settings (files) and let me know whether the problem persists? Thanks!

**Comment by bjoluc** [comment]
I hope you were able to sort this out @LB336. I'll close this issue assuming it is specific to your modifications in the MIDI Remote Mapping Assistant, but feel free to reply here if your problems persist.
